# This file was generated by GoReleaser. DO NOT EDIT.
class Fileserver < Formula
  desc "fileserver - a fileserver"
  homepage "https://github.com/fileserver"
  version "0.1.21"

  if OS.mac?
    url "https://github.com/broothie/fileserver/releases/download/v0.1.21/fileserver_0.1.21_darwin_amd64.tar.gz"
    sha256 "24a6baa19f1a2b25cd6bec7a17396728beed3d93fd3f1ca4969d19af4734be4b"
  elsif OS.linux?
    url "https://github.com/broothie/fileserver/releases/download/v0.1.21/fileserver_0.1.21_linux_amd64.tar.gz"
    sha256 "b7eca842fc9a2ea3cb0a8cf99c73ed297bf9fdabcb8dfbeb49f15dc43a799e4c"
  end

  def install
    bin.install "fileserver"
  end
end
