# This file was generated by GoReleaser. DO NOT EDIT.
class Fileserver < Formula
  desc "fileserver - a fileserver"
  homepage "https://github.com/fileserver"
  version "0.1.22"

  if OS.mac?
    url "https://github.com/broothie/fileserver/releases/download/v0.1.22/fileserver_0.1.22_darwin_amd64.tar.gz"
    sha256 "a5a8bcc9336e9580dbbee6ab160e6990dfddbcfe091cf0950873f211d36eff14"
  elsif OS.linux?
    url "https://github.com/broothie/fileserver/releases/download/v0.1.22/fileserver_0.1.22_linux_amd64.tar.gz"
    sha256 "f2ddec92ad6adf6e022dc833fb8f4e5ecb326c545c3a6ec4ecc8d1f3f262686a"
  end

  def install
    bin.install "fileserver"
  end
end
